# The URL the site will be built for
title = "JinwangMok"
base_url = "https://jinwang.me"
description = "Effort to fill with Code & Love."
theme = "duckquill"
author = "Jinwang Mok"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true
generate_feeds = true
# feed_filenames = ["rss.xml", "atom.xml"]
feed_filenames = ["rss.xml"]

taxonomies = [{name = "tags", feed = true}]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[extra]
default_theme = "dark"
source_url = "https://github.com/JinwangMok/JinwangMok.github.io"
issues_url = "https://github.com/JinwangMok/JinwangMok.github.io/issues"
show_copy_button = true

[extra.footer]
show_copyright = true
show_powered_by = true
show_source = true
socials = [
  # SVGs taken from https://simpleicons.org and encoded using https://yoksel.github.io/url-encoder/
  { url = "https://github.com/JinwangMok", name = "GitHub", icon = "%3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EGitHub%3C/title%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E" },
]

[extra.nav]
show_feed = true
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/about/_index.md", name = "About" },
]